# docker-compose.yml
services:
  db:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seaquail
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: